# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenVersion: '3.8.6'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build Maven Project'
    steps:
    - task: UseJavaVersion@0
      inputs:
        version: '11'
        addToPath: true

    - task: UseMaven@0
      inputs:
        mavenVersionOption: 'Path'
        mavenDirectory: $(Agent.ToolsDirectory)/maven/$(mavenVersion)
        mavenSetM2Home: false

    - script: 'mvn clean package'
      displayName: 'Build with Maven'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        artifactName: 'drop'


